server:
  port: 1100

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${WEATHER_DB_IP:localhost}:${WEATHER_DB_PORT:5432}/weatherapianalysisdatabase
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:111111}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: weatherapianalysis

open-weather-api:
  api-url: http://api.openweathermap.org/
  api-key: ${OPEN_WEATHER_API_KEY:default-key}
  air-pollution-url: ${open-weather-api.api-url}/data/2.5/air_pollution/history
  geocode-url: ${open-weather-api.api-url}/geo/1.0/direct
  api-call-limit: 60

resilience4j:
  circuit breaker:
    instances:
      geocodeClient:  # Configuration for the circuit breaker instance for GeocodeClient
        slidingWindowSize: 10  # Number of calls recorded before calculating failure rate
        failureRateThreshold: 50  # Percentage of failed calls before opening the circuit breaker (50% failures)
        waitDurationInOpenState: 10000  # Time (in milliseconds) the circuit stays open before switching to half-open state (10 seconds)
        permittedNumberOfCallsInHalfOpenState: 5  # Number of test calls allowed when the circuit is in half-open state
        automaticTransitionFromOpenToHalfOpenEnabled: true  # Automatically transition to half-open after wait duration

      openWeatherClient:  # Configuration for the circuit breaker instance for OpenWeatherClient
        slidingWindowSize: 10  # Number of requests stored in the sliding window before evaluating failure rate
        failureRateThreshold: 50  # Circuit breaker will open when 50% of the calls fail
        waitDurationInOpenState: 10000  # Circuit stays open for 10 seconds before transitioning to half-open
        permittedNumberOfCallsInHalfOpenState: 5  # Allow 5 test calls in half-open state before deciding to close or reopen
        automaticTransitionFromOpenToHalfOpenEnabled: true  # Enables automatic transition from open to half-open state

# SWAGGER
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  override-with-generic-response: false

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true